### PR TITLE
Move the example to a script.

### PR DESCRIPTION
**Pull request by brixen**

### CODE REVIEW

**Comment by brixen** [comment]
As I mentioned in the 2nd commit, it's stylistic so no worries if you don't want to merge it.

GitHub automatically combined these commits, so I can revert the 2nd if you don't want it.

**Comment by lucianolev** [comment]
@brixen It's perfect. Thanks!

**Comment by brixen** [comment]
@lucianolev no problem, thanks for merging. If you'll be continuing to work in this repo, I'll add more examples and info about execution on Rubinius once I fix the instance variable state on core Ruby classes so stuff like IceNine won't break.

**Comment by lucianolev** [comment]
@brixen Sure, why not :) 
I'm trying to remove ice_nine dep on unparser now.. They seem to be using it to freeze some constants in a few non-important places...

**Pull request merged**
